{% set version = "2.0.0" %}

package:
  name: r-robis
  version: {{ version }}

source:
  fn: robis_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/robis_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/robis/robis_{{ version }}.tar.gz
  sha256: 9eb06f3f95b1684fba3f391dd2411ea8eeb6ba5f87ee76afb606fe2cec1de751

build:
  noarch: generic
  number: 0
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-dplyr
    - r-httr
    - r-jsonlite
    - r-leaflet
  run:
    - r-base
    - r-dplyr
    - r-httr
    - r-jsonlite
    - r-leaflet

test:
  commands:
    - $R -e "library('robis')"  # [not win]
    - "\"%R%\" -e \"library('robis')\""  # [win]

about:
  home: https
  license: MIT
  license_file: LICENSE
  summary: Client for the Ocean Biogeographic Information System (<http
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
