{% set version = "2.6.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-robis
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/robis_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/robis/robis_{{ version }}.tar.gz
  sha256: 009d75b0b7b6b7653b5b34d400749335a5e65d348a65b01e4664f12d78316ce8

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-httpcache
    - r-httr
    - r-jsonlite
    - r-leaflet
    - r-mapedit
    - r-rlang
    - r-sf
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-httpcache
    - r-httr
    - r-jsonlite
    - r-leaflet
    - r-mapedit
    - r-rlang
    - r-sf
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('robis')"           # [not win]
    - "\"%R%\" -e \"library('robis')\""  # [win]

about:
  home: https://github.com/iobis/robis
  license: MIT
  summary: Client for the Ocean Biogeographic Information System (<https://obis.org>).
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: robis
# Title: Ocean Biogeographic Information System (OBIS) Client
# Description: Client for the Ocean Biogeographic Information System (<https://obis.org>).
# Version: 2.1.8
# Date: 2019-06-01
# Authors@R: c( person("Pieter", "Provoost", , "pieterprovoost@gmail.com", c("cre", "aut")), person("Samuel", "Bosch", , "mail@samuelbosch.com", role = "aut"), person("Ward", "Appeltans", role = "ctb"), person(, "OBIS", , "support@iobis.org", role = "cph") )
# URL: https://github.com/iobis/robis
# BugReports: https://github.com/iobis/robis/issues
# Depends: R (>= 3.1.3)
# Imports: httr, dplyr, jsonlite, leaflet, ggplot2
# License: MIT + file LICENSE
# Suggests: testthat
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-06-01 13:43:29 UTC; pieter
# Author: Pieter Provoost [cre, aut], Samuel Bosch [aut], Ward Appeltans [ctb], OBIS [cph]
# Maintainer: Pieter Provoost <pieterprovoost@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-06-03 13:20:08 UTC
