appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Q59JjhEOQ8FYC2GTZNJ/BVxzOvSSuZ2Qmb8zm1MVscIpXjfm/pDGBDw+NObyyaY8gXN5dAkKt74NLcOwiViOjvi6qHqbmwFWenoR8NNArZpv8b7lNYrQMJczH4kGKkn/2ZCTtcsjR+2T0kVGk6vnnLS6HUpAXh2T71h0e1dlh04IbsoVx81VxA10WrEvW71yhudL/NyJx8/iBtmL5zLJ6Hso3pYpU+yOSb1XmlObH1zyuSu7rG+xtIbxmFWWn8wqsZiBMNYrQ5/a03tPdhVFNDoQ1qVVBFuM0jk+aqqdvxag0N1s42QrNJHB/r8gI0qmgZrPYr+o5SI2KyHm7hlmduEMZPTj2YNSRWKyN/ES7D29+eW+Qv1zw61PN79jKGhp7QA2PXD6t7G1ttCgMlodui08EASm0WMfsFg6UAWfszpejtBSilhjNi2itv7/N+BXilOEnly49Qn1qH3eSKM9r8spT97ylQgXFPrl96Jj2rsXdZWf60Dph3mQETFHhRSBLwHpr6baxWcUbJv848dPa2FXeoE2OUB1GQf+Ajk7oWMj1q4Ow7LrIgrLgI7zLjWBiqtYgfzkktH+SG+GMdLxoXXlGlpP4a1ep34LD5RyBUqTnDJEsFXCXs3eX5Qk66LCbFfmmVu0pwKAOcTnqvWnlFPDzZ25sFRbNYDG8HR9oiU=
conda_forge_output_validation: false
